apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edc-db
spec:
  selector:
    matchLabels:
      app: edc-db
  template:
    metadata:
      labels:
        app: edc-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          envFrom:
            - configMapRef:
                name: edc-config # You'll need to create this for your .env variables
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: edc-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
